Attribute VB_Name = "Module2"



Global msgs As New Collection

Sub fillTable()

Dim winMsg() As String
  
 push winMsg(), " WM_USER = &H400"
 push winMsg(), " WM_ACTIVATE = &H6"
 push winMsg(), " WM_ACTIVATEAPP = &H1C"
 push winMsg(), " WM_ASKCBFORMATNAME = &H30C"
 push winMsg(), " WM_CANCELJOURNAL = &H4B"
 push winMsg(), " WM_CANCELMODE = &H1F"
 push winMsg(), " WM_CHANGECBCHAIN = &H30D"
 push winMsg(), " WM_CHAR = &H102"
 push winMsg(), " WM_CHARTOITEM = &H2F"
 push winMsg(), " WM_CHILDACTIVATE = &H22"
 push winMsg(), " WM_CHOOSEFONT_GETLOGFONT = (WM_USER + 1)"
 push winMsg(), " WM_CHOOSEFONT_SETFLAGS = (WM_USER + 102)"
 push winMsg(), " WM_CHOOSEFONT_SETLOGFONT = (WM_USER + 101)"
 push winMsg(), " WM_CLEAR = &H303"
 push winMsg(), " WM_CLOSE = &H10"
 push winMsg(), " WM_COMMAND = &H111"
 push winMsg(), " WM_COMPACTING = &H41"
 push winMsg(), " WM_COMPAREITEM = &H39"
 push winMsg(), " WM_CONVERTREQUESTEX = &H108"
 push winMsg(), " WM_COPY = &H301"
 push winMsg(), " WM_COPYDATA = &H4A"
 push winMsg(), " WM_CREATE = &H1"
 push winMsg(), " WM_CTLCOLORBTN = &H135"
 push winMsg(), " WM_CTLCOLORDLG = &H136"
 push winMsg(), " WM_CTLCOLOREDIT = &H133"
 push winMsg(), " WM_CTLCOLORLISTBOX = &H134"
 push winMsg(), " WM_CTLCOLORMSGBOX = &H132"
 push winMsg(), " WM_CTLCOLORSCROLLBAR = &H137"
 push winMsg(), " WM_CTLCOLORSTATIC = &H138"
 push winMsg(), " WM_CUT = &H300"
 push winMsg(), " WM_DDE_FIRST = &H3E0"
 push winMsg(), " WM_DDE_ACK = (WM_DDE_FIRST + 4)"
 push winMsg(), " WM_DDE_ADVISE = (WM_DDE_FIRST + 2)"
 push winMsg(), " WM_DDE_DATA = (WM_DDE_FIRST + 5)"
 push winMsg(), " WM_DDE_EXECUTE = (WM_DDE_FIRST + 8)"
 push winMsg(), " WM_DDE_INITIATE = (WM_DDE_FIRST)"
 push winMsg(), " WM_DDE_LAST = (WM_DDE_FIRST + 8)"
 push winMsg(), " WM_DDE_POKE = (WM_DDE_FIRST + 7)"
 push winMsg(), " WM_DDE_REQUEST = (WM_DDE_FIRST + 6)"
 push winMsg(), " WM_DDE_UNADVISE = (WM_DDE_FIRST + 3)"
 push winMsg(), " WM_DDE_TERMINATE = (WM_DDE_FIRST + 1)"
 push winMsg(), " WM_DEADCHAR = &H103"
 push winMsg(), " WM_DELETEITEM = &H2D"
 push winMsg(), " WM_DESTROY = &H2"
 push winMsg(), " WM_DESTROYCLIPBOARD = &H307"
 push winMsg(), " WM_DEVMODECHANGE = &H1B"
 push winMsg(), " WM_DRAWCLIPBOARD = &H308"
 push winMsg(), " WM_DRAWITEM = &H2B"
 push winMsg(), " WM_DROPFILES = &H233"
 push winMsg(), " WM_ENABLE = &HA"
 push winMsg(), " WM_ENDSESSION = &H16"
 push winMsg(), " WM_ENTERIDLE = &H121"
 push winMsg(), " WM_ENTERMENULOOP = &H211"
 push winMsg(), " WM_ERASEBKGND = &H14"
 push winMsg(), " WM_EXITMENULOOP = &H212"
 push winMsg(), " WM_FONTCHANGE = &H1D"
 push winMsg(), " WM_GETDLGCODE = &H87"
 push winMsg(), " WM_GETFONT = &H31"
 push winMsg(), " WM_GETHOTKEY = &H33"
 push winMsg(), " WM_GETMINMAXINFO = &H24"
 push winMsg(), " WM_GETTEXT = &HD"
 push winMsg(), " WM_GETTEXTLENGTH = &HE"
 push winMsg(), " WM_HOTKEY = &H312"
 push winMsg(), " WM_HSCROLL = &H114"
 push winMsg(), " WM_HSCROLLCLIPBOARD = &H30E"
 push winMsg(), " WM_ICONERASEBKGND = &H27"
 push winMsg(), " WM_IME_CHAR = &H286"
 push winMsg(), " WM_IME_COMPOSITION = &H10F"
 push winMsg(), " WM_IME_COMPOSITIONFULL = &H284"
 push winMsg(), " WM_IME_ENDCOMPOSITION = &H10E"
 push winMsg(), " WM_IME_KEYDOWN = &H290"
 push winMsg(), " WM_IME_KEYLAST = &H10F"
 push winMsg(), " WM_IME_KEYUP = &H291"
 push winMsg(), " WM_IME_NOTIFY = &H282"
 push winMsg(), " WM_IME_SELECT = &H285"
 push winMsg(), " WM_IME_SETCONTEXT = &H281"
 push winMsg(), " WM_IME_STARTCOMPOSITION = &H10D"
 push winMsg(), " WM_INITDIALOG = &H110"
 push winMsg(), " WM_INITMENU = &H116"
 push winMsg(), " WM_INITMENUPOPUP = &H117"
 push winMsg(), " WM_KEYDOWN = &H100"
 push winMsg(), " WM_KEYFIRST = &H100"
 push winMsg(), " WM_KEYLAST = &H108"
 push winMsg(), " WM_KEYUP = &H101"
 push winMsg(), " WM_KILLFOCUS = &H8"
 push winMsg(), " WM_LBUTTONDBLCLK = &H203"
 push winMsg(), " WM_LBUTTONDOWN = &H201"
 push winMsg(), " WM_LBUTTONUP = &H202"
 push winMsg(), " WM_MBUTTONDBLCLK = &H209"
 push winMsg(), " WM_MBUTTONDOWN = &H207"
 push winMsg(), " WM_MBUTTONUP = &H208"
 push winMsg(), " WM_MDIACTIVATE = &H222"
 push winMsg(), " WM_MDICASCADE = &H227"
 push winMsg(), " WM_MDICREATE = &H220"
 push winMsg(), " WM_MDIDESTROY = &H221"
 push winMsg(), " WM_MDIGETACTIVE = &H229"
 push winMsg(), " WM_MDIICONARRANGE = &H228"
 push winMsg(), " WM_MDIMAXIMIZE = &H225"
 push winMsg(), " WM_MDINEXT = &H224"
 push winMsg(), " WM_MDIREFRESHMENU = &H234"
 push winMsg(), " WM_MDIRESTORE = &H223"
 push winMsg(), " WM_MDISETMENU = &H230"
 push winMsg(), " WM_MDITILE = &H226"
 push winMsg(), " WM_MEASUREITEM = &H2C"
 push winMsg(), " WM_MENUCHAR = &H120"
 push winMsg(), " WM_MENUSELECT = &H11F"
 push winMsg(), " WM_MOUSEACTIVATE = &H21"
 push winMsg(), " WM_MOUSEFIRST = &H200"
 push winMsg(), " WM_MOUSELAST = &H209"
 push winMsg(), " WM_MOUSEMOVE = &H200"
 push winMsg(), " WM_MOVE = &H3"
 push winMsg(), " WM_NCACTIVATE = &H86"
 push winMsg(), " WM_NCCALCSIZE = &H83"
 push winMsg(), " WM_NCCREATE = &H81"
 push winMsg(), " WM_NCDESTROY = &H82"
 push winMsg(), " WM_NCHITTEST = &H84"
 push winMsg(), " WM_NCLBUTTONDBLCLK = &HA3"
 push winMsg(), " WM_NCLBUTTONDOWN = &HA1"
 push winMsg(), " WM_NCLBUTTONUP = &HA2"
 push winMsg(), " WM_NCMBUTTONDBLCLK = &HA9"
 push winMsg(), " WM_NCMBUTTONDOWN = &HA7"
 push winMsg(), " WM_NCMBUTTONUP = &HA8"
 push winMsg(), " WM_NCMOUSEMOVE = &HA0"
 push winMsg(), " WM_NCPAINT = &H85"
 push winMsg(), " WM_NCRBUTTONDBLCLK = &HA6"
 push winMsg(), " WM_NCRBUTTONDOWN = &HA4"
 push winMsg(), " WM_NCRBUTTONUP = &HA5"
 push winMsg(), " WM_NEXTDLGCTL = &H28"
 push winMsg(), " WM_NULL = &H0"
 push winMsg(), " WM_PAINT = &HF"
 push winMsg(), " WM_PAINTCLIPBOARD = &H309"
 push winMsg(), " WM_PAINTICON = &H26"
 push winMsg(), " WM_PALETTECHANGED = &H311"
 push winMsg(), " WM_PALETTEISCHANGING = &H310"
 push winMsg(), " WM_PARENTNOTIFY = &H210"
 push winMsg(), " WM_PASTE = &H302"
 push winMsg(), " WM_PENWINFIRST = &H380"
 push winMsg(), " WM_PENWINLAST = &H38F"
 push winMsg(), " WM_POWER = &H48"
 push winMsg(), " WM_PSD_ENVSTAMPRECT = (WM_USER + 5)"
 push winMsg(), " WM_PSD_FULLPAGERECT = (WM_USER + 1)"
 push winMsg(), " WM_PSD_GREEKTEXTRECT = (WM_USER + 4)"
 push winMsg(), " WM_PSD_MARGINRECT = (WM_USER + 3)"
 push winMsg(), " WM_PSD_MINMARGINRECT = (WM_USER + 2)"
 push winMsg(), " WM_PSD_PAGESETUPDLG = (WM_USER)"
 push winMsg(), " WM_PSD_YAFULLPAGERECT = (WM_USER + 6)"
 push winMsg(), " WM_QUERYDRAGICON = &H37"
 push winMsg(), " WM_QUERYENDSESSION = &H11"
 push winMsg(), " WM_QUERYNEWPALETTE = &H30F"
 push winMsg(), " WM_QUERYOPEN = &H13"
 push winMsg(), " WM_QUEUESYNC = &H23"
 push winMsg(), " WM_QUIT = &H12"
 push winMsg(), " WM_RBUTTONDBLCLK = &H206"
 push winMsg(), " WM_RBUTTONDOWN = &H204"
 push winMsg(), " WM_RBUTTONUP = &H205"
 push winMsg(), " WM_RENDERALLFORMATS = &H306"
 push winMsg(), " WM_RENDERFORMAT = &H305"
 push winMsg(), " WM_SETCURSOR = &H20"
 push winMsg(), " WM_SETFOCUS = &H7"
 push winMsg(), " WM_SETFONT = &H30"
 push winMsg(), " WM_SETHOTKEY = &H32"
 push winMsg(), " WM_SETREDRAW = &HB"
 push winMsg(), " WM_SETTEXT = &HC"
 push winMsg(), " WM_SHOWWINDOW = &H18"
 push winMsg(), " WM_SIZE = &H5"
 push winMsg(), " WM_SIZECLIPBOARD = &H30B"
 push winMsg(), " WM_SPOOLERSTATUS = &H2A"
 push winMsg(), " WM_SYSCHAR = &H106"
 push winMsg(), " WM_SYSCOLORCHANGE = &H15"
 push winMsg(), " WM_SYSCOMMAND = &H112"
 push winMsg(), " WM_SYSDEADCHAR = &H107"
 push winMsg(), " WM_SYSKEYDOWN = &H104"
 push winMsg(), " WM_SYSKEYUP = &H105"
 push winMsg(), " WM_TIMECHANGE = &H1E"
 push winMsg(), " WM_TIMER = &H113"
 push winMsg(), " WM_UNDO = &H304"
 push winMsg(), " WM_VKEYTOITEM = &H2E"
 push winMsg(), " WM_VSCROLL = &H115"
 push winMsg(), " WM_VSCROLLCLIPBOARD = &H30A"
 push winMsg(), " WM_WINDOWPOSCHANGED = &H47"
 push winMsg(), " WM_WINDOWPOSCHANGING = &H46"
  
 On Error Resume Next 'multiple msgs with same val =err
 For i = 0 To UBound(winMsg)
    t = Split(winMsg(i), " = ")
    msgs.Add Trim(t(0)), Trim(t(1))
 Next

 Erase winMsg()
 
End Sub



Sub push(ary, value) 'this modifies parent ary object
    On Error GoTo init
    x = UBound(ary) '<-throws Error If Not initalized
    ReDim Preserve ary(UBound(ary) + 1)
    ary(UBound(ary)) = value
    Exit Sub
init:     ReDim ary(0): ary(0) = value
End Sub


